max_width = 100
edition = "2018"

# automatically replace R { x: x } with R { x }
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true

# disable alphabetical reordering within groups
reorder_imports = false
reorder_modules = false
reorder_impl_items = false

indent_style = "Visual"
imports_indent = "Visual"
imports_layout = "Mixed"
imports_granularity = "Preserve"
group_imports = "Preserve"

newline_style = "Unix"
use_small_heuristics = "Default"

type_punctuation_density = "Wide"
fn_args_layout = "Tall"

remove_nested_parens = true
combine_control_expr = true

wrap_comments = false

unstable_features = true

# ignore = ["src/api/pontem.rs"]
